language: python
python:
  - '3.5'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - PYTHONPATH=.:djangoproject py.test -k "not djangoproject"
  - PYTHONPATH=. py.test djangoproject
notifications:
  slack:
    secure: LfKPIzFzqSWmK+ccNWzy005WXUFSDQ0iVGPUNgAerg0fSR8XTKpxaMkp0JtcHOIvD9wyNMZ43gItBiEBX2BVyB//4RO2PpLokBDYVtKV8N9LcCjlGPI/7JoglhmA2zBMuplAQO8QHQM50xd6vdDbvF+UxvlPyg8XX+/qGPmadYzQwjZL5iYIt214zXfQI613HmPFFjdzwY//v8sAe2MV8jjBO/0q3bS+DgSxE9HEzDOBZEsEyFOFgch2xBGqk2W6TvDnDewuktnMgfifC4pL93PyUjiFPm6aIWBJU6WgP6DoOWebXWzeRSsqufR3c8Nkzo7c1J91obNwCANhUPG4ZpkaASgyQve/eipWSeqaexGsxSLOfXcfPtpznfRerikFQ+dn5gTV1AEvslRZhBt2VPY6yJ38Z4k56+cxCU6mLyU9Dn0uKD7TWDUuYLQtesb6n8eayKdY29UiuXeHvHG1KdjCtW/wIJys8Qq3ey64CQd2EB2QmRtymWutvq2I87G0H9BFR2YYdjOc0U4Edmc09LaBodsdoU9mEHhcrr8O7xGaNrA1o9ih8yuD25Q0otmOZ123IOGHeiaLMuzD9MXRVNO/utbHRkiW28AFbDZHkgu6VIKkj5odw+wBrOAJx1Jyf163l9mXztc9AADZN4Bw04Y308jTf1/u+Nj0YsUc3yM=
